<a href="https://colab.research.google.com/github/JFish72/CSC-349-Machine-Learning-/blob/main/HW2/data_prep_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

df = pd.read_csv('cybersecurity_intrusion_data.csv')
df.head()

,session_id,network_packet_size,protocol_type,login_attempts,session_duration,encryption_used,ip_reputation_score,failed_logins,browser_type,unusual_time_access,attack_detected
0,SID_00001,599,TCP,4,492.983263,DES,0.606818,1,Edge,0,1
1,SID_00002,472,TCP,3,1557.996461,DES,0.301569,0,Firefox,0,0
2,SID_00003,629,TCP,3,75.044262,DES,0.739164,2,Chrome,0,1
3,SID_00004,804,UDP,4,601.248835,DES,0.123267,0,Unknown,0,1
4,SID_00005,453,TCP,5,532.540888,AES,0.054874,1,Firefox,0,0

In [7]:
import pandas as pd

df = pd.read_csv('cybersecurity_intrusion_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9537 entries, 0 to 9536
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   session_id           9537 non-null   object
 1   network_packet_size  9537 non-null   int64
 2   protocol_type        9537 non-null   object
 3   login_attempts       9537 non-null   int64
 4   session_duration     9537 non-null   float64
 5   encryption_used      7571 non-null   object
 6   ip_reputation_score  9537 non-null   float64
 7   failed_logins        9537 non-null   int64
 8   browser_type         9537 non-null   object
 9   unusual_time_access  9537 non-null   int64
 10  attack_detected      9537 non-null   int64
dtypes: float64(2), int64(5), object(4)
memory usage: 819.7+ KB

In [11]:
import pandas as pd

df = pd.read_csv('cybersecurity_intrusion_data.csv')

df.describe()

,network_packet_size,login_attempts,session_duration,ip_reputation_score,failed_logins,unusual_time_access,attack_detected
count,9537.000000,9537.000000,9537.000000,9537.000000,9537.000000,9537.000000,9537.000000
mean,500.430639,4.032086,792.745312,0.331338,1.517773,0.149942,0.447101
std,198.379364,1.963012,786.560144,0.177175,1.033988,0.357034,0.497220
min,64.000000,1.000000,0.500000,0.002497,0.000000,0.000000,0.000000
25%,365.000000,3.000000,231.953006,0.191946,1.000000,0.000000,0.000000
50%,499.000000,4.000000,556.277457,0.314778,1.000000,0.000000,0.000000
75%,635.000000,5.000000,1105.380602,0.453388,2.000000,0.000000,1.000000
max,1285.000000,13.000000,7190.392213,0.924299,5.000000,1.000000,1.000000

In [13]:
import pandas as pd

df = pd.read_csv('cybersecurity_intrusion_data.csv')
df["protocol_type"].value_counts()

protocol_type
TCP     6624
UDP     2406
ICMP     507
Name: count, dtype: int64

In [39]:
import pandas as pd

df = pd.read_csv('cybersecurity_intrusion_data.csv')
df["encryption_used"].value_counts()

encryption_used
AES    4706
DES    2865
Name: count, dtype: int64

In [43]:
import pandas as pd

df = pd.read_csv('cybersecurity_intrusion_data.csv')
df["encryption_used"].isnull().sum()

np.int64(1966)

In [42]:
import pandas as pd

df = pd.read_csv('cybersecurity_intrusion_data.csv')

df["encryption_used"] = df["encryption_used"].fillna(df["encryption_used"].mode()[0])
df["encryption_used"].isnull().sum()

np.int64(0)

In [65]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

df = pd.read_csv('cybersecurity_intrusion_data.csv')

X = df.drop(columns = ["attack_detected"])
Y = df["attack_detected"]

categorical_columns = X.select_dtypes(include=["object"]).columns
numerical_columns = X.select_dtypes(include=["number"]).columns

numerical_pipeline = Pipeline([("imputer", SimpleImputer(strategy = "median")), ("Scaler", StandardScaler())])

catergorical_pipeline = Pipeline([("imputer", SimpleImputer(strategy = "most_frequent")), ("encoder", OneHotEncoder())])

preprocessor = ColumnTransformer([("numerical", numerical_pipeline, numerical_columns), ("categorical", catergorical_pipeline, categorical_columns)])

pipeline = Pipeline([("preprocessor", preprocessor)])

transformed = pipeline.fit_transform(X)

pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('Scaler',
                                                                   StandardScaler())]),
                                                  Index(['network_packet_size', 'login_attempts', 'session_duration',
       'ip_reputation_score', 'failed_logins', 'unusual_time_access'],
      dtype='object')),
                                                 ('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder())]),
                                                  Index(['session_id', 'protocol_type', 'encryption_used', 'browser_type'], dtype='object'))]))])